name: Fetch GitHub Contributions REST

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  

      - name: Get latest commit
        run: |
          repos=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/users/sarahthebest/repos?per_page=100" | jq -r '.[] | select(.fork == false) | .name')

          repo_data_array=()
          latest_commit_repository=""
          latest_commit_message=""
          latest_commit_date=""

          for repo in $repos; do
            echo "Checking latest commit in repository: $repo"
            commit=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/sarahthebest/$repo/commits?per_page=1" | jq -r '.[0]')
            
            commit_message=$(echo "$commit" | jq -r '.commit.message')
            commit_date=$(echo "$commit" | jq -r '.commit.committer.date')

            repo_data_array+=("{\"repository\": \"$repo\", \"message\": \"$commit_message\", \"date\": \"$commit_date\"}")

            if [[ -n "$commit_date" ]]; then
              if [[ -z "$latest_commit_date" || "$commit_date" > "$latest_commit_date" ]]; then
                latest_commit_date="$commit_date"
                latest_commit_message="$commit_message"
                latest_commit_repository="$repo"
              fi
            fi
          done

          json_output="{\"repositories\": [$(IFS=,; echo "${repo_data_array[*]}")], \"latest_commit\": {\"repository\": \"$latest_commit_repository\", \"message\": \"$latest_commit_message\", \"date\": \"$latest_commit_date\"}}"
          echo $json_output > src/assets/json/gh_data.json

      - name: Configure Git user
        run: |
          git config --global user.name 'sarahthebest'
          git config --global user.email 'sarah.emmoth@proton.me'

      - name: Commit and Push to GitHub Pages branch
        run: |
          git add src/assets/json/gh_data.json
          git commit -m "Update contributions data" || echo "No changes to commit"
          git push origin main
