name: Fetch GitHub Contributions REST

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  

      - name: Fetch repository data with REST API
        run: |
          repos=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/users/sarahthebest/repos?per_page=100" | jq -r '.[] | select(.fork == false) | .name')

          repo_data_array=()

          for repo in $repos; do
            echo "Checking latest commit in repository: $repo"
            commit=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/sarahthebest/$repo/commits?per_page=1" | jq -r '.[0]')
            
            commit_message=$(echo "$commit" | jq -r '.commit.message')
            commit_date=$(echo "$commit" | jq -r '.commit.committer.date')

            repo_data_array+=("{\"repository\": \"$repo\", \"message\": \"$commit_message\", \"date\": \"$commit_date\"}")
          done

          echo "{\"repositories\": [${repo_data_array[*]}]}" > src/assets/json/gh_data.json

      - name: Configure Git user
        run: |
          git config --global user.name 'sarahthebest'
          git config --global user.email 'sarah.emmoth@proton.me'

      - name: Commit and Push to GitHub Pages branch
        run: |
          git add src/assets/json/gh_data.json
          git commit -m "Update GitHub data" || echo "No changes to commit"
          git push origin main
